//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIVICIO_FARMACIA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFarmaciaEntities : DbContext
    {
        public BDFarmaciaEntities()
            : base("name=BDFarmaciaEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<DESCUENTO> DESCUENTOS { get; set; }
        public virtual DbSet<DOMICILIO> DOMICILIOS { get; set; }
        public virtual DbSet<FARMACEUTA> FARMACEUTAs { get; set; }
        public virtual DbSet<HISTORIALVENTA> HISTORIALVENTAS { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIOs { get; set; }
        public virtual DbSet<INYECTOLOGIA> INYECTOLOGIAs { get; set; }
        public virtual DbSet<PAGO> PAGOS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<PROVEEDORE> PROVEEDORES { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOS { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSALs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VENTA> VENTAS { get; set; }
        public virtual DbSet<VENTASPRODUCTO> VENTASPRODUCTOS { get; set; }
    }
}
