//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIVICIO_FARMACIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMICILIO
    {
        public int IDDomicilios { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string DireccionEntrega { get; set; }
        public Nullable<decimal> TotalPago { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
