//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIVICIO_FARMACIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FARMACEUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FARMACEUTA()
        {
            this.INYECTOLOGIAs = new HashSet<INYECTOLOGIA>();
        }
    
        public int IDFarmaceuta { get; set; }
        public Nullable<long> Documento { get; set; }
        public Nullable<int> IDSucursal { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaContratacion { get; set; }

        [JsonIgnore]
        public virtual SUCURSAL SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INYECTOLOGIA> INYECTOLOGIAs { get; set; }
    }
}
