//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIVICIO_FARMACIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int IDPago { get; set; }
        public Nullable<int> IDVenta { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> ValorPago { get; set; }
    
        public virtual VENTA VENTA { get; set; }
    }
}
