//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERIVICIO_FARMACIA.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.HISTORIALVENTAS = new HashSet<HISTORIALVENTA>();
            this.INVENTARIOs = new HashSet<INVENTARIO>();
            this.VENTASPRODUCTOS = new HashSet<VENTASPRODUCTO>();
        }
    
        public int IDProducto { get; set; }
        public int IDCategoria { get; set; }
        public int IDProveedor { get; set; }
        public string Nombreproducto { get; set; }
        public string Descripcion { get; set; }
        public string Presentacion { get; set; }
        public string Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }

        [JsonIgnore]
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<HISTORIALVENTA> HISTORIALVENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<INVENTARIO> INVENTARIOs { get; set; }
        [JsonIgnore]
        public virtual PROVEEDORE PROVEEDORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTASPRODUCTO> VENTASPRODUCTOS { get; set; }
    }
}
